class rundeck_server::params {
    $rundeck_server_acl_policies                           = hiera_hash( 'rundeck_server::acl_policies', {} )
    $rundeck_server_acl_policies_disabled                  = hiera_hash( 'rundeck_server::acl_policies_disabled', {} )
    $rundeck_server_admin_username                         = hiera( 'rundeck_server::admin_username', 'admin' )
    $rundeck_server_admin_password                         = hiera( 'rundeck_server::admin_password' )
    $rundeck_server_bind_url                               = hiera( 'rundeck_server::bind_url' )
    $rundeck_server_bind_user_dn                           = hiera( 'rundeck_server::bind_user_dn' )
    $rundeck_server_bind_user_adn_attribute                = hiera( 'rundeck_server::bind_user_rdn_attribute', 'uid' )
    $rundeck_server_bind_user_id_attribute                 = hiera( 'rundeck_server::bind_user_id_attribute', 'uid' )
    $rundeck_server_bind_user_password_attribute           = hiera( 'rundeck_server::bind_user_password_attribute', 'userPassword' )
    $rundeck_server_bind_user_object_class                 = hiera( 'rundeck_server::bind_user_object_class', 'posixAccount' )
    $rundeck_server_bind_role_dn                           = hiera( 'rundeck_server::bind_role_dn' )
    $rundeck_server_bind_role_name_attribute               = hiera( 'rundeck_server::bind_role_name_attribute', 'cn' )
    $rundeck_server_bind_role_username_member_attribute    = hiera( 'rundeck_server::bind_role_username_member_attribute', 'memberUid' )
    $rundeck_server_bind_role_member_attribute             = hiera( 'rundeck_server::bind_role_member_attribute', 'memberUid' )
    $rundeck_server_bind_role_object_class                 = hiera( 'rundeck_server::bind_role_object_class', 'posixGroup' )
    $rundeck_server_conf_dir                               = hiera( 'rundeck_server::conf_dir', '/etc/rundeck' )
    $rundeck_server_var_dir                                = hiera( 'rundeck_server::var_dir', '/var/lib/rundeck' )
    $rundeck_server_config                                 = hiera_hash( 'rundeck_server::config', {} )
    $rundeck_server_hostname                               = hiera( 'rundeck_server::hostname', "rundeck.${sigma_tld}" )
    $rundeck_server_port                                   = hiera( 'rundeck_server::port', '4440' )
    $rundeck_server_plugins                                = hiera_array( 'rundeck_server::plugins', [] )
    $rundeck_server_plugins_dir                            = hiera( 'rundeck_server::plugins_dir', "${rundeck_server_var_dir}/exp/webapp/plugins" )
    $rundeck_server_packages                               = hiera_array( 'rundeck_server::packages', [ 'rundeck' ] )
    $rundeck_server_url                                    = hiera( 'rundeck_server::url', "http://${rundeck_server_hostname}:${rundeck_server_port}" )
    $rundeck_server_database_driver                        = hiera( 'rundeck_server::database_driver', '' )
    $rundeck_server_database_url                           = hiera( 'rundeck_server::database_url', 'jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true;TRACE_LEVEL_FILE=4' )
    $rundeck_server_database_username                      = hiera( 'rundeck_server::database_username', '' )
    $rundeck_server_database_password                      = hiera( 'rundeck_server::database_password', '' )
    $rundeck_server_project_dir                            = hiera( 'rundeck_server::project_dir', '/var/rundeck/projects/${project.name}' )
    $rundeck_server_project_etc_dir                        = hiera( 'rundeck_server::project_etc_dir', '/var/rundeck/projects/${project.name}/etc' )
    $rundeck_server_project_resources_file                 = hiera( 'rundeck_server::project_resources_file', '/var/rundeck/projects/${project.name}/etc/resources.xml' )
}
