class cloudera_manager::params {
    $cloudera_version                          = hiera( 'cloudera::version', "present" )
    $cloudera_cname                            = hiera( 'cloudera::cname' )
    $cloudera_manage_server                    = hiera( 'cloudera::manage_server', "true" )
    $cloudera_enable_server                    = hiera( 'cloudera::enable_server', "true" )

    #  The ${cloudera_db_password} can be optionally specified as a host/hostgroup/global Foreman parameter
    $cloudera_db_password                      = hiera( 'cloudera_manager::db_password', "$cloudera_mgr_db_password" )
    $cloudera_master_packages                  = hiera( 'cloudera_manager::master_packages', [ 'cloudera-manager-server', 'cloudera-manager-server-db-2' ] )
    $cloudera_mgr_db_type                      = hiera( 'cloudera_manager::mgr_db_type', "postgresql" )
    $cloudera_mgr_db_setuptype                 = hiera( 'cloudera_manager::mgr_db_setuptype', "EMBEDDED" )
    $cloudera_mgr_db_host                      = hiera( 'cloudera_manager::mgr_db_host', "localhost" )
    $cloudera_mgr_db_port                      = hiera( 'cloudera_manager::mgr_db_port', "7432" )
    $cloudera_mgr_db_name                      = hiera( 'cloudera_manager::mgr_db_name', "scm" )
    $cloudera_mgr_db_user                      = hiera( 'cloudera_manager::mgr_db_user', "scm" )
    $cloudera_am_db_password                   = hiera( 'cloudera_manager::am_db_password', "$cloudera_am_db_password" )
    $cloudera_am_db_type                       = hiera( 'cloudera_manager::am_db_type', "postgresql" )
    $cloudera_am_db_host                       = hiera( 'cloudera_manager::am_db_host', "localhost" )
    $cloudera_am_db_port                       = hiera( 'cloudera_manager::am_db_port', "7432" )
    $cloudera_am_db_name                       = hiera( 'cloudera_manager::am_db_name', "amon" )
    $cloudera_am_db_user                       = hiera( 'cloudera_manager::am_db_user', "amon" )
    $cloudera_rm_db_password                   = hiera( 'cloudera_manager::rm_db_password', "$cloudera_rm_db_password" )
    $cloudera_rm_db_type                       = hiera( 'cloudera_manager::rm_db_type', "postgresql" )
    $cloudera_rm_db_host                       = hiera( 'cloudera_manager::rm_db_host', "localhost" )
    $cloudera_rm_db_port                       = hiera( 'cloudera_manager::rm_db_port', "7432" )
    $cloudera_rm_db_name                       = hiera( 'cloudera_manager::rm_db_name', "rman" )
    $cloudera_rm_db_user                       = hiera( 'cloudera_manager::rm_db_user', "rman" )
    $cloudera_nav_db_password                  = hiera( 'cloudera_manager::nav_db_password', "$cloudera_nav_db_password" )
    $cloudera_nav_db_type                      = hiera( 'cloudera_manager::nav_db_type', "postgresql" )
    $cloudera_nav_db_host                      = hiera( 'cloudera_manager::nav_db_host', "localhost" )
    $cloudera_nav_db_port                      = hiera( 'cloudera_manager::nav_db_port', "7432" )
    $cloudera_nav_db_name                      = hiera( 'cloudera_manager::nav_db_name', "nav" )
    $cloudera_nav_db_user                      = hiera( 'cloudera_manager::nav_db_user', "nav" )
    $cloudera_navms_db_password                = hiera( 'cloudera_manager::navms_db_password', "$cloudera_navms_db_password" )
    $cloudera_navms_db_type                    = hiera( 'cloudera_manager::navms_db_type', "postgresql" )
    $cloudera_navms_db_host                    = hiera( 'cloudera_manager::navms_db_host', "localhost" )
    $cloudera_navms_db_port                    = hiera( 'cloudera_manager::navms_db_port', "7432" )
    $cloudera_navms_db_name                    = hiera( 'cloudera_manager::navms_db_name', "navms" )
    $cloudera_navms_db_user                    = hiera( 'cloudera_manager::navms_db_user', "navms" )
}
